#! /usr/bin/python2
import gtk.gdk
import sys

if len(sys.argv) == 1:
    print("Missing operand")
else:
    try:
        w = gtk.gdk.window_foreign_new( gtk.gdk.get_default_root_window().property_get("_NET_ACTIVE_WINDOW")[2][0] )
        w.set_decorations(int(sys.argv[1]))
        gtk.gdk.window_process_all_updates()
        gtk.gdk.flush()
    except:
        print("Accepted values: 0 1")
